#!/usr/bin/env bash
# =========================================================================
# Certbot setup on Hetzner — one-time.
#   - Installs certbot
#   - Creates webroot directory for ACME challenges
#   - Adds location block to nginx for /.well-known/acme-challenge/
#   - Mounts webroot into nginx container via docker-compose override
#   - Verifies both domains serve /.well-known/ correctly before issuing certs
# Idempotent. Run on Hetzner as: sudo ./00-setup.sh
# =========================================================================

set -euo pipefail

[[ $EUID -eq 0 ]] || { echo "Run with sudo"; exit 1; }

CAREAI_DIR="/home/deploy/careai"
WEBROOT="/var/www/certbot"

echo "=== 1. Install certbot ==="
if command -v certbot >/dev/null 2>&1; then
  echo "  certbot already installed: $(certbot --version)"
else
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -qq -y certbot
fi

echo
echo "=== 2. Create webroot ==="
mkdir -p "${WEBROOT}/.well-known/acme-challenge"
chown -R deploy:deploy "${WEBROOT}"
chmod -R 755 "${WEBROOT}"
echo "  created: ${WEBROOT}"

echo
echo "=== 3. Create/update docker-compose override to mount webroot ==="
OVERRIDE_FILE="${CAREAI_DIR}/docker-compose.override.yml"

# Check if our marker is already in the override file
if [[ -f "${OVERRIDE_FILE}" ]] && grep -q "certbot-webroot-mount" "${OVERRIDE_FILE}"; then
  echo "  override already present — skipping"
else
  # Preserve any existing override content
  if [[ -f "${OVERRIDE_FILE}" ]]; then
    cp "${OVERRIDE_FILE}" "${OVERRIDE_FILE}.bak.$(date +%s)"
  fi
  cat > "${OVERRIDE_FILE}" <<EOF
# Auto-generated by certbot/00-setup.sh — DO NOT EDIT the certbot-webroot-mount section
# Adds webroot volume for Let's Encrypt HTTP-01 challenges
services:
  nginx:
    volumes:
      # certbot-webroot-mount
      - ${WEBROOT}:/var/www/certbot:ro
EOF
  chown deploy:deploy "${OVERRIDE_FILE}"
  echo "  wrote: ${OVERRIDE_FILE}"
fi

echo
echo "=== 4. Add ACME location block to nginx configs ==="

inject_acme_block() {
  local conf="$1"
  if grep -q "acme-challenge" "$conf"; then
    echo "  ACME block already in $(basename "$conf") — skipping"
    return 0
  fi

  cp "$conf" "$conf.bak.$(date +%s)"

  # Use Python for safe regex substitution (falls back to sed if no python3)
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$conf" <<'PYEOF'
import re, sys
path = sys.argv[1]
with open(path) as f:
    content = f.read()

acme_block = """
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }
"""

# Match first port-80 server block and inject after first server_name
def add_acme(m):
    block = m.group(0)
    if 'acme-challenge' in block:
        return block
    return re.sub(r'(server_name[^;]*;)', r'\1' + acme_block, block, count=1)

pattern = re.compile(r'server\s*\{[^{}]*?listen\s+80\b[^{}]*?\}', re.DOTALL)
new_content, n = pattern.subn(add_acme, content, count=1)

if n > 0 and new_content != content:
    with open(path, 'w') as f:
        f.write(new_content)
    print(f"  ✓ added ACME block to {path}")
else:
    print(f"  ⚠ no port 80 server block found in {path} — please add manually")
    sys.exit(2)
PYEOF
  else
    echo "  python3 not available — please add the location block manually:"
    echo ""
    echo "    location /.well-known/acme-challenge/ {"
    echo "        root /var/www/certbot;"
    echo "        allow all;"
    echo "    }"
    echo ""
    echo "  Inside the 'listen 80' server block of $conf"
    return 1
  fi
}

inject_acme_block "${CAREAI_DIR}/nginx.conf"
inject_acme_block "${CAREAI_DIR}/nginx-docsign.conf"

echo
echo "=== 5. Recreate nginx container with new volume + configs ==="
cd "${CAREAI_DIR}"
sudo -u deploy docker compose \
  -f docker-compose.yml \
  -f docker-compose.docsign.yml \
  -f docker-compose.override.yml \
  up -d --force-recreate nginx

echo "  waiting 5s for nginx to settle…"
sleep 5

echo
echo "=== 6. Verify nginx serves /.well-known/ ==="
TEST_FILE="test-$(date +%s)"
echo "acme-test-content" > "${WEBROOT}/.well-known/acme-challenge/${TEST_FILE}"
chown deploy:deploy "${WEBROOT}/.well-known/acme-challenge/${TEST_FILE}"

all_ok=true
for domain in careaisoftware.co.uk signsimple.co.uk; do
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "http://${domain}/.well-known/acme-challenge/${TEST_FILE}")
  if [[ "$code" == "200" ]]; then
    echo "  ✓ http://${domain}/.well-known/acme-challenge/${TEST_FILE} → 200"
  else
    echo "  ✗ http://${domain}/.well-known/acme-challenge/${TEST_FILE} → ${code}"
    all_ok=false
  fi
done

rm -f "${WEBROOT}/.well-known/acme-challenge/${TEST_FILE}"

echo
if $all_ok; then
  echo "=== ✓ SETUP COMPLETE ==="
  echo "Next: sudo ./01-issue-certs.sh"
else
  echo "=== ⚠ SETUP NEEDS ATTENTION ==="
  echo "At least one domain didn't serve the ACME challenge — investigate before issuing certs."
  echo "Check nginx logs:  docker logs --tail 50 careai-nginx"
  exit 1
fi
