#!/usr/bin/env bash
# =========================================================================
# Certbot setup on Hetzner — one-time.
#
# Assumes nginx.conf and nginx-docsign.conf on the server ALREADY have
# the /.well-known/acme-challenge/ location block (managed via git in
# care-ai repo, rsync'd to production).
#
# This script:
#   - Installs certbot
#   - Creates webroot directory for ACME challenges
#   - Creates docker-compose.override.yml to mount webroot into nginx
#   - Recreates nginx container with the new volume mount
#   - Verifies both domains serve /.well-known/ correctly
#
# Idempotent. Run on Hetzner as: sudo ./00-setup.sh
# =========================================================================

set -euo pipefail

[[ $EUID -eq 0 ]] || { echo "Run with sudo"; exit 1; }

CAREAI_DIR="/home/deploy/careai"
WEBROOT="/var/www/certbot"

echo "=== 1. Install certbot ==="
if command -v certbot >/dev/null 2>&1; then
  echo "  certbot already installed: $(certbot --version)"
else
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -qq -y certbot
fi

echo
echo "=== 2. Create webroot ==="
mkdir -p "${WEBROOT}/.well-known/acme-challenge"
chown -R deploy:deploy "${WEBROOT}"
chmod -R 755 "${WEBROOT}"
echo "  created: ${WEBROOT}"

echo
echo "=== 3. Verify nginx configs have ACME location block ==="
missing_acme=false
for conf in "${CAREAI_DIR}/nginx.conf" "${CAREAI_DIR}/nginx-docsign.conf"; do
  if grep -q "acme-challenge" "${conf}"; then
    echo "  ✓ $(basename "${conf}") has acme-challenge block"
  else
    echo "  ✗ $(basename "${conf}") MISSING acme-challenge block"
    missing_acme=true
  fi
done

if ${missing_acme}; then
  echo
  echo "⚠ One or more nginx configs are missing the acme-challenge location block."
  echo "  Update them in git (care-ai repo) and rsync to this server before continuing:"
  echo
  echo "    # On your Mac:"
  echo "    cd /Users/praveen.r/Projects/github/care-ai/care-ai"
  echo "    rsync -av nginx.conf nginx-docsign.conf hetzner-prod:~/careai/"
  echo
  exit 1
fi

echo
echo "=== 4. Create/update docker-compose override to mount webroot ==="
OVERRIDE_FILE="${CAREAI_DIR}/docker-compose.override.yml"

if [[ -f "${OVERRIDE_FILE}" ]] && grep -q "certbot-webroot-mount" "${OVERRIDE_FILE}"; then
  echo "  override already present — skipping"
else
  [[ -f "${OVERRIDE_FILE}" ]] && cp "${OVERRIDE_FILE}" "${OVERRIDE_FILE}.bak.$(date +%s)"
  cat > "${OVERRIDE_FILE}" <<EOF
# Auto-generated by certbot/00-setup.sh — DO NOT edit the certbot-webroot-mount section
# Adds webroot volume for Let's Encrypt HTTP-01 challenges
services:
  nginx:
    volumes:
      # certbot-webroot-mount
      - ${WEBROOT}:/var/www/certbot:ro
EOF
  chown deploy:deploy "${OVERRIDE_FILE}"
  echo "  wrote: ${OVERRIDE_FILE}"
fi

echo
echo "=== 5. Recreate nginx container with new volume ==="
cd "${CAREAI_DIR}"
sudo -u deploy docker compose \
  -f docker-compose.yml \
  -f docker-compose.docsign.yml \
  -f docker-compose.override.yml \
  up -d --force-recreate nginx

echo "  waiting 5s for nginx to settle…"
sleep 5

echo
echo "=== 6. Verify nginx serves /.well-known/ correctly ==="
TEST_FILE="test-$(date +%s)"
echo "acme-test-content" > "${WEBROOT}/.well-known/acme-challenge/${TEST_FILE}"
chown deploy:deploy "${WEBROOT}/.well-known/acme-challenge/${TEST_FILE}"

all_ok=true
for domain in careaisoftware.co.uk signsimple.co.uk; do
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "http://${domain}/.well-known/acme-challenge/${TEST_FILE}")
  if [[ "$code" == "200" ]]; then
    echo "  ✓ http://${domain}/.well-known/acme-challenge/${TEST_FILE} → 200"
  else
    echo "  ✗ http://${domain}/.well-known/acme-challenge/${TEST_FILE} → ${code}"
    all_ok=false
  fi
done

echo
echo "=== 7. Verify regular HTTPS redirect still works ==="
for domain in careaisoftware.co.uk signsimple.co.uk; do
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "http://${domain}/")
  if [[ "$code" == "301" ]]; then
    echo "  ✓ http://${domain}/ → ${code} (redirects to HTTPS)"
  else
    echo "  ⚠ http://${domain}/ → ${code} (expected 301)"
  fi
done

rm -f "${WEBROOT}/.well-known/acme-challenge/${TEST_FILE}"

echo
if $all_ok; then
  echo "=== ✓ SETUP COMPLETE ==="
  echo "Next: sudo ./01-issue-certs.sh"
else
  echo "=== ⚠ SETUP NEEDS ATTENTION ==="
  echo "At least one domain didn't serve the ACME challenge — investigate before issuing certs."
  echo "Check nginx logs:  docker logs --tail 50 careai-nginx"
  exit 1
fi
